"""Init

Revision ID: 0a3d63407780
Revises: ddc6c2a29f0e
Create Date: 2023-04-07 13:05:05.348381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a3d63407780'
down_revision = 'ddc6c2a29f0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('contacts', sa.Column('surname', sa.String(length=50), nullable=False))
    op.drop_column('contacts', 'last_name')
    op.drop_column('contacts', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('contacts', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('contacts', 'surname')
    op.drop_column('contacts', 'name')
    # ### end Alembic commands ###
